imports:
  - { resource: easyadmin/menu.yaml }
  - { resource: easyadmin/basic.yaml }
  - { resource: easyadmin/user.yaml }
  - { resource: easyadmin/device.yaml }
#  - { resource: easyadmin/government_data.yaml }
