parameters:
    app.path.map_icons: /uploads/images/map-icons

vich_uploader:
    db_driver: orm

    mappings:
        icon_map:
            uri_prefix: /uploads/images/map-icons
            upload_destination: '%kernel.project_dir%/public/uploads/images/map-icons'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
