easy_admin:
    site_name: 'Administration backend'
    design:
        form_theme:
            - 'vertical'
        assets:
            css:
                - '/css/styles.css'
#    entities:
#         List the entity class name you want to manage
#        - App\Entity\Camera
#        - App\Entity\Device
#        - App\Entity\DeviceModel
