easy_admin:
    site_name: 'Administration backend'
    disabled_actions: ['show']
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: 'delete', icon: 'trash', label: '' }
    design:
        form_theme:
            - 'vertical'
            - 'easyadmin/form/fields.html.twig'
        assets:
            css:
                - '/bootstrap-datepicker/css/bootstrap-datepicker3.min.css'
                - '/css/styles.css'
            js:
                - '/bootstrap-datepicker/js/bootstrap-datepicker.min.js'
                - '/bootstrap-datepicker/locales/bootstrap-datepicker.es.min.js'
                - '/js/custom-js.js'
#    entities:
#         List the entity class name you want to manage
#        - App\Entity\Camera
#        - App\Entity\Device
#        - App\Entity\DeviceModel
