easy_admin:
    site_name: 'Administration backend'
    design:
        form_theme:
            - 'vertical'
#    entities:
        # List the entity class name you want to manage
#        - App\Entity\UserRole
#        - App\Entity\Device
#        - App\Entity\DeviceModel
