easy_admin:
    entities:
        Device:
            class: App\Entity\Device
            list:
              fields:
                - { property: 'authDevice', label: 'Imei' }
                - 'label'
                - { property: 'iddevicemodel', label: 'Model' }
                - 'client'
                - { property: 'sim', label: 'Phone number' }
                - { property: 'iconMap', type: 'image', base_path: '%app.path.map_icons%' }
            form:
              fields:
                - { property: 'authDevice', css_class: 'col-lg-6', label: 'Imei' }
                - { property: 'label', css_class: 'col-lg-6', type_options: {required: true} }
                - { property: 'iddevicemodel', label: 'Model', css_class: 'col-lg-6' }
                - { property: 'client', label: 'Client', css_class: 'col-lg-6' }
                - { property: 'sim', label: 'Phone number', css_class: 'col-lg-6' }
                - { property: 'routeName', css_class: 'col-lg-6' }
                - { property: 'economicNumber', css_class: 'col-lg-6' }
                - { property: 'vehiclePlate', css_class: 'col-lg-6' }
                - { property: 'iconMapFile', type: 'vich_image', css_class: 'col-lg-6' }
                - { property: 'panicButton', label: 'Has panic button', css_class: 'col-lg-6' }
#                - { property: 'devicesGroup', type_options: {by_reference: false} }

        DeviceModel:
            class: App\Entity\DeviceModel
        ClientDevice:
            class: App\Entity\Device
            list:
                fields:
                  - { property: 'authDevice', label: 'Imei' }
                  - 'label'
                  - { property: 'iddevicemodel', label: 'Model' }
        Group:
            class: App\Entity\Group
            list:
                fields:
#                  - 'id'
                  - 'label'
                  - 'devices'
            form:
                fields:
                  - 'label'
                  - { property: 'devices', type_options: {by_reference: false} }

