easy_admin:
    entities:
        Dispositivo:
            class: App\Entity\Device
#            disabled_actions: ['delete', 'show']
            templates:
              list: 'easyadmin/device/list.html.twig'
            list:
              actions:
                - { name: 'startvpnlist', icon: 'wifi', css_class: 'btn btn-sm btn-primary', label: '', title: 'Iniciar VPN' }
              dql_filter: "entity.trashed != 1 or entity.trashed is null"
              fields:
                - { property: 'authDevice', label: 'Imei' }
                - { property: 'label', label: 'Nombre' }
                - { property: 'iddevicemodel', label: 'Modelo' }
                - { property: 'client', label: 'Cliente' }
                - { property: 'sim', label: 'Número de teléfono' }
                - { property: 'routeName', label: 'Ruta' }
#                - { property: 'economicNumber', label: 'Número económico' }
#                - { property: 'vehiclePlate', label: 'Número de placa' }
                - { property: 'vehicle', label: 'Vehículo' }
#                - { property: 'iconMap', type: 'image', base_path: '%app.path.map_icons%' }
            form:
              fields:
                - { property: 'authDevice', css_class: 'col-lg-6', label: 'Imei', type_options: {disabled: true} }
                - { property: 'label', label: 'Nombre', css_class: 'col-lg-6', type_options: {required: true} }
                - { property: 'iddevicemodel', label: 'Modelo', css_class: 'col-lg-6' }
                - { property: 'client', label: 'Cliente', css_class: 'col-lg-6' }
                - { property: 'sim', label: 'Número de teléfono', css_class: 'col-lg-6' }
#                - { property: 'routeName', label: 'Ruta', css_class: 'col-lg-6' }
#                - { property: 'economicNumber', label: 'Número económico', css_class: 'col-lg-6' }
#                - { property: 'vehiclePlate', label: 'Número de placa', css_class: 'col-lg-6' }
#                - { property: 'iconMapFile', type: 'vich_image', css_class: 'col-lg-6' }
                - { property: 'panicButton', label: 'Transporte público', css_class: 'col-lg-6' }
#                - { property: 'devicesGroup', type_options: {by_reference: false} }
            edit:
              actions:
                - { name: 'startvpn', icon: 'wifi', css_class: 'btn btn-sm btn-primary', label: 'Iniciar VPN', title: 'Iniciar VPN' }

        DeviceModel:
            class: App\Entity\DeviceModel
        ClientDevice:
            class: App\Entity\Device
            list:
                fields:
                  - { property: 'authDevice', label: 'Imei' }
                  - 'label'
                  - { property: 'iddevicemodel', label: 'Model' }
        Grupo:
            class: App\Entity\Group
            list:
                fields:
#                  - 'id'
                  - { property: 'label', label: 'Nombre' }
                  - { property: 'devices', label: 'Dispositivos' }
            form:
                fields:
                  - { property: 'label', label: 'Nombre', css_class: 'col-lg-6' }
                  - { property: 'devices', type_options: {by_reference: false} }
        DispositivoDeCliente:
            disabled_actions: ['show', 'delete', 'new']
            class: App\Entity\Device
#            disabled_actions: ['delete', 'show']
            templates:
              list: 'easyadmin/device/list.html.twig'
            list:
              title: 'Dispositivos'
              dql_filter: "entity.trashed != 1 or entity.trashed is null"
              fields:
                - { property: 'authDevice', label: 'Imei' }
                - { property: 'label', label: 'Nombre' }
                - { property: 'iddevicemodel', label: 'Modelo' }
                - { property: 'client', label: 'Cliente' }
                - { property: 'sim', label: 'Número de teléfono' }
#                - { property: 'routeName', label: 'Ruta' }
#                - { property: 'economicNumber', label: 'Número económico' }
#                - { property: 'vehiclePlate', label: 'Número de placa' }
                - { property: 'vehicle', label: 'Vehículo' }
                - { property: 'lastGpsDate', type: 'date', label: 'Última Fecha Recibido'}
                - { property: 'lastGpsTime', type: 'time', label: 'Última Hora Recibido'}

#                - { property: 'iconMap', type: 'image', base_path: '%app.path.map_icons%' }
            form:
              fields:
#                        - { property: 'authDevice', css_class: 'col-lg-6', label: 'Imei' }
                - { property: 'label', label: 'Nombre', css_class: 'col-lg-6', type_options: {required: true} }
#                        - { property: 'iddevicemodel', label: 'Modelo', css_class: 'col-lg-6' }
#                        - { property: 'client', label: 'Cliente', css_class: 'col-lg-6' }
                - { property: 'sim', label: 'Número de teléfono', css_class: 'col-lg-4' }
#                - { property: 'routeName', label: 'Ruta', css_class: 'col-lg-6' }
#                - { property: 'economicNumber', label: 'Número económico', css_class: 'col-lg-6' }
#                - { property: 'vehiclePlate', label: 'Número de placa', css_class: 'col-lg-6' }
#                - { property: 'iconMapFile', type: 'vich_image', css_class: 'col-lg-6' }
#                        - { property: 'panicButton', label: 'Transporte público', css_class: 'col-lg-6' }
#                - { property: 'devicesGroup', type_options: {by_reference: false} }
            edit:
              title: 'Modificar Dispositivo'
        DispositivoMDVR:
            disabled_actions: ['show', 'edit']
            class: App\Entity\Device
#            disabled_actions: ['delete', 'show']
            templates:
              list: 'easyadmin/mdvr/list.html.twig'
            list:
              title: 'Dispositivos MDVR'
              dql_filter: "(entity.iddevicemodel = 3) and entity.trashed != 1 or entity.trashed is null"
              fields:
                - { property: 'authDevice', label: 'Imei' }
                - { property: 'label', label: 'Nombre' }
                - { property: 'iddevicemodel', label: 'Modelo' }
                - { property: 'client', label: 'Cliente' }
                - { property: 'sim', label: 'Número de teléfono' }
#                - { property: 'routeName', label: 'Ruta' }
#                - { property: 'economicNumber', label: 'Número económico' }
#                - { property: 'vehiclePlate', label: 'Número de placa' }
                - { property: 'vehicle', label: 'Vehículo' }
#                - { property: 'lastGpsDate', type: 'date', label: 'Última Fecha Recibido'}
#                - { property: 'lastGpsTime', type: 'time', label: 'Última Hora Recibido'}
