easy_admin:
  design:
    menu:
      - { label: 'GPS', role: 'ROLE_USER' }
      - { label: 'Dashboard', route: 'backend_dashboard', default: true, icon: 'dashboard ', role: ROLE_USER }
#      - { label: 'Dashboard', default: true, icon: 'dashboard ' }
#      - { entity: 'Admin', label: 'Admins',  icon: 'users', role: 'ROLE_ADMIN'}
      - { entity: 'Administrador', label: 'Admins',  icon: 'vcard', role: 'ROLE_ADMIN'}
      - { entity: 'Cliente', label: 'Clientes',  icon: 'users', role: 'ROLE_ADMIN'}
#      - { entity: 'ClientDevice', label: 'Devices Assigned',  icon: 'truck', role: 'ROLE_CLIENT'}

#      - { label: 'Crear Dispositivo', icon: 'list', role: 'ROLE_ADMIN' }
#      - { entity: 'DispositivoMDVR', label: 'API (MDVR)', params: { action: 'list' }, icon: 'plus', role: 'ROLE_ADMIN'}
#      - { entity: 'Dispositivo', label: 'Formulario', params: { action: 'new' }, icon: 'plus', role: 'ROLE_ADMIN'}

      - { label: 'Dispositivos', icon: 'list', role: 'ROLE_ADMIN' }
      - { entity: 'Dispositivo', label: 'Dispositivos',  icon: 'truck', role: 'ROLE_ADMIN'}
      - { entity: 'Dispositivo', label: 'Dispositivos',  icon: 'truck', role: 'ROLE_ADMIN_USER'}
      - { entity: 'DispositivoDeCliente', label: 'Dispositivos',  icon: 'truck', role: 'ROLE_CLIENT'}
#      - { label: 'MDVR', icon: 'list', role: 'ROLE_CLIENT' }
#      - { entity: 'Usuario', label: 'Usuarios',  icon: 'users', role: 'ROLE_CLIENT'}
      - { label: 'GRUPOS', icon: 'list', role: 'ROLE_CLIENT' }
      - { entity: 'Grupo', label: 'Grupos',  icon: 'list', role: 'ROLE_CLIENT'}
#      - { entity: 'GovernmentData', label: 'Government Forms',  icon: 'file-o', role: 'ROLE_ADMIN'}
      - { label: 'CAMARAS', icon: 'list', role: 'ROLE_ADMIN' }
      - { entity: 'Camara', label: 'Camaras',  icon: 'camera', role: 'ROLE_ADMIN'}

      - { label: 'SEMOV', icon: 'list', role: 'ROLE_ADMIN' }
      - { entity: 'SemovLog', label: 'Trazas SEMOV',  icon: 'list', role: 'ROLE_ADMIN'}

      - { label: 'Empleados', role: 'ROLE_CLIENT' }
      - { entity: 'Empleado', label: 'Empleados', params: { action: 'list' }, icon: 'list', role: 'ROLE_CLIENT'}
#      - { entity: 'Empleado', label: 'Nuevo Empleado', params: { action: 'new' }, icon: 'plus', role: 'ROLE_CLIENT'}

      - { label: 'Vehículos', role: 'ROLE_CLIENT' }
      - { entity: 'Vehiculo', label: 'Vehículos', params: { action: 'list' }, icon: 'list', role: 'ROLE_CLIENT'}
      - { entity: 'Mantenimiento', label: 'Mantenimientos', params: { action: 'list' }, icon: 'wrench', role: 'ROLE_CLIENT'}
      - { entity: 'MantenimientoCerrado', label: 'Mant. Cerrados', params: { action: 'list' }, icon: 'times-circle', role: 'ROLE_CLIENT'}
#      - { entity: 'Vehiculo', label: 'Adicionar vehículo', params: { action: 'new' }, icon: 'plus', role: 'ROLE_CLIENT'}

      - { label: 'Neumáticos', role: 'ROLE_CLIENT' }
      - { entity: 'Neumatico', label: 'Neumáticos', params: { action: 'list' }, icon: 'list', role: 'ROLE_CLIENT'}
#      - { entity: 'Neumatico', label: 'Alta Nuevo/Usado', params: { action: 'new' }, icon: 'plus', role: 'ROLE_CLIENT'}
#      - { entity: 'NeumaticoRenovado', label: ' Alta Renovado', params: { action: 'new' }, icon: 'plus', role: 'ROLE_CLIENT'}
      - { entity: 'Deposito', label: 'En Deposito', params: { action: 'list' }, icon: 'list', role: 'ROLE_CLIENT'}
      - { entity: 'Renovar', label: 'Enviados a renovar', params: { action: 'list' }, icon: 'list', role: 'ROLE_CLIENT'}
      - { entity: 'Baja', label: 'Dados de baja', params: { action: 'list' }, icon: 'list', role: 'ROLE_CLIENT'}

      - { label: 'Tags',  icon: 'tag', role: 'ROLE_CLIENT' }
      - { entity: 'Tag', label: 'Tags', params: { action: 'list' }, icon: 'list', role: 'ROLE_CLIENT'}
#      - { entity: 'Tag', label: 'Nuevo Tag', params: { action: 'new' }, icon: 'plus', role: 'ROLE_CLIENT'}

      - { label: 'Revisiones', icon: 'list', role: 'ROLE_CLIENT' }
      - { entity: 'Revision', label: 'Revisiones', params: { action: 'list' }, icon: 'list', role: 'ROLE_CLIENT'}

      - { entity: 'ApiOptions', label: 'Contraseña API', params: { action: 'edit' }, icon: 'edit', role: 'ROLE_ADMIN'}
