easy_admin:
    entities:
        SemovLog:
            class: App\Entity\SemovLog
            list:
              title: 'Trazas SEMOV'
              disabled_actions: ['new', 'edit', 'delete']
              fields:
                - { property: 'id', label: 'Id' }
                - { property: 'createdAt', label: 'Fecha' }
