easy_admin:
    entities:
        SemovLog:
            class: App\Entity\SemovLog
            list:
              title: 'Trazas de llamadas hechas a web api SEMOV'
              actions: ['show']
              fields:
                - { property: 'id', label: 'Id' }
                - { property: 'createdAt', label: 'Fecha' }
