easy_admin:
    entities:
        SemovLog:
            class: App\Entity\SemovLog
            disabled_actions: ['new', 'edit', 'delete']
            list:
              title: 'Trazas SEMOV'
              actions:
                - { name: 'show', icon: 'show' }
              fields:
                - { property: 'id', label: 'Id' }
                - { property: 'createdAt', label: 'Fecha' }
