easy_admin:
    entities:
        SemovLog:
            class: App\Entity\SemovLog
            disabled_actions: ['new', 'edit', 'delete']
            list:
                title: 'Trazas SEMOV'
                actions:
                  - { name: 'show', icon: 'search', label: false, title: 'Ver Resultados' }
                fields:
                  - { property: 'id', label: 'Id' }
                  - { property: 'createdAt', label: 'Fecha', format: 'm/d/Y H:i:s' }
            show:
                title: 'Resultado de la api SEMOV'
                fields:
                  - { property: 'createdAt', label: 'Fecha', format: 'm/d/Y H:i:s', css_class: 'col-sm-4' }
                  - { property: 'dataArray', label: 'Información', template: 'easyadmin/templates/semov_data.html.twig', css_class: 'col-sm-12' }
