easy_admin:
    entities:
        SemovLog:
            class: App\Entity\SemovLog
            disabled_actions: ['new', 'edit', 'delete']
            list:
                title: 'Trazas SEMOV'
                actions:
                  - { name: 'show', icon: 'search', label: false, title: 'Ver Resultados' }
                fields:
                  - { property: 'id', label: 'Id' }
                  - { property: 'createdAt', label: 'Fecha', format: 'm/d/Y H:i:s' }
            show:
                design:
                  assets:
                    css:
                      #                - '/bootstrap-datepicker/css/bootstrap-datepicker3.min.css'
                      - '/Datatables/datatables.css'
                    js:
                      - '/Datatables/datatables.js'

                title: 'Resultado de la api SEMOV'
                fields:
                  - { property: 'createdAt', label: 'Fecha', format: 'm/d/Y H:i:s' }
                  - { property: 'dataArray', label: 'Información', template: 'easyadmin/templates/semov_data.html.twig' }
