easy_admin:
  entities:
    Vehiculo:
      class: App\Entity\Vehicle
      list:
#        actions: ['-new']
        fields:
          - { property: 'name', label: 'Nombre o número económico', type_options: { block_name: 'custom_type' } }
          - { property: 'plateNumber', label: 'Número de placa' }
          - { property: 'model', label: 'Modelo' }
          - { property: 'type', label: 'Tipo', type: 'text' }
          - { property: 'year', label: 'Año' }
          - { property: 'route', label: 'Ruta' }
          - { property: 'odometer', label: 'Odómetro' }
          - { property: 'device', label: 'Dispositivo' }
      form:
#        actions: ['-list']
        title: 'Adicionar vehículo'
        fields:
          - { property: 'name', css_class: 'col-lg-4', label: 'Nombre o número económico', type_options: { block_name: 'custom_type' } }
          - { property: 'plateNumber', label: 'Número de placa', css_class: 'col-lg-4' }
          - { property: 'model', label: 'Modelo', css_class: 'col-lg-4' }
          - { property: 'type', label: 'Tipo', type: 'text', css_class: 'col-lg-4' }
          - { property: 'year', label: 'Año', css_class: 'col-lg-4' }
          - { property: 'route', label: 'Ruta', css_class: 'col-lg-4' }
          - { property: 'odometer', label: 'Odómetro', css_class: 'col-lg-4' }
          - { property: 'device', label: 'Dispositivo', css_class: 'col-lg-4' }
      edit:
        title: 'Editar vehículo'